# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


########################################################
import sys
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow, QMessageBox, QPushButton
from PyQt5.QtWidgets import QStyleFactory
from GUI_v2_Options import Ui_OptionWindow
from GUI_v2_Start import Ui_SignalTranslator
########################################################


# noinspection PyAttributeOutsideInit
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 270, 141, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 521, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpciones = QtWidgets.QMenu(self.menubar)
        self.menuOpciones.setObjectName("menuOpciones")
        self.menuOpciones.setStyleSheet("QMenuBar {background-color: red; }")
        MainWindow.setMenuBar(self.menubar)
        self.actionProbar_Camara = QtWidgets.QAction(MainWindow)
        self.actionProbar_Camara.setObjectName("actionProbar_Camara")
        self.actionVer_Palabras = QtWidgets.QAction(MainWindow)
        self.actionVer_Palabras.setObjectName("actionVer_Palabras")
        self.actionSalir_Aplicacion = QtWidgets.QAction(MainWindow)
        self.actionSalir_Aplicacion.setObjectName("actionSalir_Aplicacion")
        self.menuOpciones.addAction(self.actionProbar_Camara)
        self.menuOpciones.addAction(self.actionVer_Palabras)
        self.menuOpciones.addSeparator()
        self.menuOpciones.addAction(self.actionSalir_Aplicacion)
        self.menubar.addAction(self.menuOpciones.menuAction())
        ########################################################

        self.actionSalir_Aplicacion.triggered.connect(MainWindow.close)
        self.actionVer_Palabras.triggered.connect(self.abrirOpciones)
        self.actionProbar_Camara.triggered.connect(self.Camera)
        self.pushButton.clicked.connect(self.Start_Video)

        ########################################################
        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Comenzar"))
        self.pushButton_2.setText(_translate("MainWindow", "Salir"))
        self.label_5.setText(_translate("MainWindow", "Bienvenido"))
        self.label_4.setText(_translate("MainWindow", "Usuario"))
        self.menuOpciones.setTitle(_translate("MainWindow", "Opciones"))
        self.actionProbar_Camara.setText(_translate("MainWindow", "Probar Camara"))
        self.actionVer_Palabras.setText(_translate("MainWindow", "Ver Palabras"))
        self.actionSalir_Aplicacion.setText(_translate("MainWindow", "Salir Aplicacion"))
########################################################

    def abrirOpciones(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_OptionWindow()
        self.ui.setupUi(self.window)
        self.window.setFixedWidth(410)
        self.window.setFixedHeight(347)
        self.window.show()

    def Start_Video(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SignalTranslator()
        self.ui.setupUi(self.window)
        self.window.setFixedWidth(686)
        self.window.setFixedHeight(526)
        self.window.show()

    def Camera(self):
        cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)
        while True:
            ret, self.frame = cap.read()
            if not ret:
                msg2 = QMessageBox()
                msg2.setWindowTitle('Camera info')
                msg2.setText('Web Cam No Conected, Closing App')
                msg2.setIcon(QMessageBox.Information)
                msg2.setStandardButtons(QMessageBox.Ok)
                x = msg2.exec_()
            self.frame = cv2.flip(self.frame, 1)
            cv2.imshow("Camara", self.frame)
            key = cv2.waitKey(1) & 0xFF
            if key == 27 or not cv2.getWindowProperty("Camara", cv2.WND_PROP_VISIBLE):
                break

        cap.release()
        cv2.destroyAllWindows()

########################################################


if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setStyle('Fusion')  # ['windowsvista', 'Windows', 'Fusion']
    app.closeAllWindows()
    w = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(w)
    w.setFixedHeight(480)
    w.setFixedWidth(640)
    w.show()
    sys.exit(app.exec_())
