# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_v2_Options.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

########################################################
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow, QMessageBox, QPushButton, QListWidget
from PyQt5.QtWidgets import QStyleFactory
import os
global categoriasT
########################################################


# noinspection PyAttributeOutsideInit
class Ui_OptionWindow(object):
    def setupUi(self, OptionWindow):
        OptionWindow.setObjectName("OptionWindow")
        OptionWindow.resize(410, 347)
        OptionWindow.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.label = QtWidgets.QLabel(OptionWindow)
        self.label.setGeometry(QtCore.QRect(40, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(OptionWindow)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(OptionWindow)
        self.pushButton.setGeometry(QtCore.QRect(290, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(0, 170, 127)")
        self.pushButton.setObjectName("pushButton")
        self.scrollPalabras = QtWidgets.QScrollArea(OptionWindow)
        self.scrollPalabras.setGeometry(QtCore.QRect(40, 50, 121, 191))
        self.scrollPalabras.setStyleSheet("")
        self.scrollPalabras.setWidgetResizable(True)
        self.scrollPalabras.setObjectName("scrollPalabras")
        self.scrollAreaPalabras = QtWidgets.QWidget()
        self.scrollAreaPalabras.setGeometry(QtCore.QRect(0, 0, 119, 189))
        self.scrollAreaPalabras.setObjectName("scrollAreaPalabras")
        self.listWidgetPalabras = QtWidgets.QListWidget(self.scrollAreaPalabras)
        self.listWidgetPalabras.setGeometry(QtCore.QRect(0, 0, 121, 192))
        self.listWidgetPalabras.setStyleSheet("    QWidget{ background-color: rgb(255, 255, 127) } \n"
                                              "    QScrollBar{ background-color: red }")
        self.listWidgetPalabras.setObjectName("listWidgetPalabras")
        self.scrollPalabras.setWidget(self.scrollAreaPalabras)
        self.scrollLetras = QtWidgets.QScrollArea(OptionWindow)
        self.scrollLetras.setGeometry(QtCore.QRect(220, 50, 120, 191))
        self.scrollLetras.setStyleSheet("")
        self.scrollLetras.setWidgetResizable(True)
        self.scrollLetras.setObjectName("scrollLetras")
        self.scrollAreaLetras = QtWidgets.QWidget()
        self.scrollAreaLetras.setGeometry(QtCore.QRect(0, 0, 118, 189))
        self.scrollAreaLetras.setObjectName("scrollAreaLetras")
        self.listWidgetLetras = QtWidgets.QListWidget(self.scrollAreaLetras)
        self.listWidgetLetras.setGeometry(QtCore.QRect(0, 0, 121, 192))
        self.listWidgetLetras.setStyleSheet("    QWidget{ background-color: rgb(255, 255, 127) } \n"
                                            "    QScrollBar{ background-color: red }")
        self.listWidgetLetras.setObjectName("listWidgetLetras")
        self.scrollLetras.setWidget(self.scrollAreaLetras)

        self.retranslateUi(OptionWindow)
        self.pushButton.clicked.connect(OptionWindow.close)
        QtCore.QMetaObject.connectSlotsByName(OptionWindow)

        ########################################################
        global categoriasT
        if not os.path.exists("DATA_SET"):
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText('Directory not found, Clossing App...')
            msg.setIcon(QMessageBox.Critical)
            msg.setStandardButtons(QMessageBox.Ok)
            x = msg.exec_()
        else:
            categoriasT = os.listdir('DATA_SET')

        for palabras in categoriasT:
            if len(palabras) > 1:
                if palabras == 'Fondo Vacio':
                    palabras.lstrip('Fondo Vacio')
                else:
                    self.listWidgetPalabras.addItem(palabras)
            elif len(palabras) == 1:
                self.listWidgetLetras.addItem(palabras)
    ########################################################

    def retranslateUi(self, OptionWindow):
        _translate = QtCore.QCoreApplication.translate
        OptionWindow.setWindowTitle(_translate("OptionWindow", "Opciones"))
        self.label.setText(_translate("OptionWindow", "Palabras Registradas"))
        self.label_2.setText(_translate("OptionWindow", "Letras Registradas"))
        self.pushButton.setText(_translate("OptionWindow", "Cerrar"))
